apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cnncg2fla-go
  janus-idp.io/tekton: cnncg2fla-go
  backstage.io/kubernetes-id: cnncg2fla-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cnncg2fla-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
