apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cnncg2fla-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnncg2fla-go 
  name: cnncg2fla-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cnncg2fla-go 
